services:
  backend:
    image: jookmaste/234-deploylab-backend:latest
    pull_policy: always
    ports:
      - "8082:8080"
    environment:
      - VITE_GRAPHQL_URI=http://44.210.16.135/graphql
      - VITE_SERVER_URI=http://44.210.16.135:8082
    restart: unless-stopped